version: '3'

services:
  orthanc:
    image: osimis/orthanc
    ports:
      - "4240:4242"
      - "8040:8042"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json
      - ./filedb/:/var/lib/orthanc/db/
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: orthancdb
    ports:
      - "6000:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data

  ohif_viewer:
    image: ohif/viewer
    container_name: ohif_regresyon
    ports:
      - 4000:80
    environment: 
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
 
