version: '3'

services:
  orthanc:
    image: osimis/orthanc
    ports:
      - "4240:4242"
      - "8040:8042"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json
      - ./filedb/:/var/lib/orthanc/db/
    depends_on:
      - mariadb
    
  mariadb:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: orthancdb
      ports:
        - "3300:3306"
      volumes:
        - ./mysqldb:/var/lib/mysql
        - ./my.cnf:/etc/mysql/my.cnf
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    
    


  ohif_viewer:
    image: ohif/viewer
    container_name: ohif_regresyon
    ports:
      - 4000:80
    environment: 
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
 
